# Generated by Django 4.1.2 on 2022-10-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactForm_name', models.CharField(max_length=122)),
                ('ContactForm_email', models.EmailField(max_length=122)),
                ('ContactForm_pnumber', models.IntegerField()),
                ('ContactForm_message', models.TextField()),
            ],
        ),
    ]
