# Generated by Django 4.1.2 on 2022-10-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('House_title', models.CharField(max_length=122)),
                ('House_des', models.TextField()),
            ],
        ),
    ]
