# Generated by Django 4.1.2 on 2022-10-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='House_image',
            field=models.FileField(max_length=250, null=True, upload_to='images/'),
        ),
    ]
