# Generated by Django 4.1.2 on 2022-10-25 05:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_house_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='House_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='House_title', unique=True),
        ),
    ]
