# Generated by Django 4.1.2 on 2022-10-26 05:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_house_house_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='House_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
